### ISSUE TITLE
Unit cap problem

### ISSUE THREAD

**Issue by gaudrik** [HW-PlayersPatch/2.3#113]
Destroyers for hw2 supposed to be at 6 for cap?

I thought only hw1 got the increase

**Comment by cloaked2222** [comment]
Ya, all races are supposed to be capped at 6 DDs.

hw2c was 5, but in HWR v1.3 all races had 7. When v2.0 was released, ppl thought 5 was too low, so we compromised and went to 6 for v2.205.
