### ISSUE TITLE
HW1 SP: autolaunch at mission start

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#114]
In HW1C it was possible to tell the MS/CC to keep the strikecrafts docked at mission end, and this setting would carry to the next mission. In HWRM, ships autolaunch at mission start regardless of how the launch behaviour was setted at the end of the previous mission.

**Comment by cloaked2222** [comment]
Might be possible in HWR? idk

**Comment by cloaked2222** [comment]
Pie in the sky
