### ISSUE TITLE
Population info

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#116]
Current display for Kushan population info:
![homeworldrm 2018-07-24 21-00-08-12](https://user-images.githubusercontent.com/39770560/43737121-6bee6286-99c0-11e8-973c-ad6604d21a79.png)

Current display for Hiigaran population info: 
![homeworldrm 2018-07-30 14-00-40-17](https://user-images.githubusercontent.com/39770560/43737018-28c9e5ca-99c0-11e8-9b56-b3004c726174.png)

I guess we have two options here:
- the first is to add a line for every ship type, so Kushans would get lines for scouts, repair/light/heavy/multigun corvettes and support/assault/ion/drone frigates and Hiigarans would get gunship/pulsar/(minelayers?) corvettes and torpedo/ion/flak/(marine?)/(defense field?) frigates;
- the second is to remove all the lines for ship types that have the same unit cap as the default family cap, so both Kushan and Hiigaran would lose ints and bombers

Thinking again, maybe the first option isn't viable because it might make the population info too long.

**Comment by cloaked2222** [comment]
In developing the 2.0 patch, i remember thinking the 'int/bomber' lines were dumb as they matched the overall population. Adding a line for every ship type would be way over-kill. On the other hand, early game it is quite useful to know exactly how many ints you have...

Prolly best to remove them for consistency, or just leave as is.

**Comment by Echo1707** [comment]
I opened two your videos and I saw the Queue menu, not the population Info one :P
That said, if one is not making scouts, they can see how many ints they have both via the Build menu on the right if the fighter production is selected or in the Info.
Also, as HW1 you can't really count the enemy fighters, and as HW2 you just count the squadrons. I think that should be removed.

I think I have an idea where to remove these lines: `scripts\rules\deathmatch\unitcaps`
`supplyLimit("Fighter", 70);`
`supplyLimit("Scout", 18);`
`supplyLimit("Interceptor", 70);`
`supplyLimit("Bomber", 70);`
`supplyLimit("LanceFighter", 70);`
`supplyLimit("Defenders", 20);`
`supplyLimit("Defensefighters", 10);`
`supplyLimit("CloakedFighters", 20);`

I'll try it tomorrow... I've been busy these last few days, but on the bright side I finally had the chance to play a multiplayer match! Was a month without playing :(

**Comment by cloaked2222** [comment]
Cool. Ya go ahead and remove the int/bomber lines then. Be sure to do it for deathmatchhw1 and deathmatchhw2 too.

Sounds like its time to get back to the lobby, and put modding on hold for a while (that's my plan anyways :p).

**Comment by cloaked2222** [comment]
Pie in the sky
