### ISSUE TITLE
Expert HW1 AI is useless

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#117]
These are some notes I took while watching a 3 Expert HW1 AI vs 3 Expert HW2 AI game (btw Cloaked, I spawned as observer, scuttled the ship and kept spectating, so I guess there is no need to have the sensor range any greated than what is needed to make the ship clearly visible both out and in the sensor manager):
- HW1: scout the enemy very little (uses only probes which are easily shot down), produce but doesn't use bombers (they attack on their own by proximity with enemy ships), CC tends to move and obstruct MS capital ship exit, strikegroups hopelessly chase after HW2 scouts (HW1 races are not able to kill them and they just bait strikegroups delaying them from reaching the front line), CCs and DDs comes way later than their HW2 races counterparts, absolutely loves making MDDs
- Kushan specific: absolutely love their drone frigs, CC tends to move towards the MS not only obstructing the MS capital ship exit but also obstructing the CC own frig exit
- HW2: loves capturing anything, from colls to MS

![homeworldrm 2018-08-06 17-19-59-75](https://user-images.githubusercontent.com/39770560/43738544-4ef11e6c-99c5-11e8-9806-6d4d0995e962.png)

I don't know why these 3 collectors are stuck:
![homeworldrm 2018-08-06 16-54-45-02](https://user-images.githubusercontent.com/39770560/43738548-5251947e-99c5-11e8-9a0f-6634dd6ffa5b.png)

**Comment by cloaked2222** [comment]
Observer sensors are for the many ppl that don't know to scuttle and keep watching. They're only the range of a scout now, so there's very little down sides to keeping it like this.

Modding the AI takes a long time to figure out, but feel free to dive in.

**Comment by cloaked2222** [comment]
Pie in the sky
