### ISSUE TITLE
hgn destroyer buildtime

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#14]
[`165 => 148 (-10%)`](https://github.com/HW-PlayersPatch/2.3/blob/Cloaked/Props/Hiigaran_Changes_Prop.md#destroyers)

I think this is fine since DDs need to be in a group of at least two for their main strengths to be apparent - cloaked disagrees and says this value doesn't need changing

keeping this here for input, but also as a reminder that I haven't undone this buff yet (need convincing)

**Comment by cloaked2222** [comment]
Definitely keep it at 165. We can play a few Hiig vs Hiig 1v1's - after figher/corv opener i go DDs, you go frigs. You'll prolly want to nerf DDs afterwards... Frig guy has a very small window of time to win, as long as DD guy can hold the game is in the bag.

**Comment by Novaras** [comment]
## Numbers

Upgraded DD will lose 100% of the time to 6 ions or 5 HMFs.
~~~
DD  x1: 2000 / 113
Ion x6: 4200 / 207
HMF x5: 3500 / 173
~~~

Assuming all upgrades, 

DDs have `119000` HP
Ions have `21500` HP
HMFs have `21500` HP

DDs are healing `94.4, 130.7` HP/s before and after upgrade, ions are healing `15.4, 21.6` HP/s before and after, HMFS are healing the same. With this in mind I'll list DPS as well as effective DPS (DPS - healing per second = effective DPS).

DDs apply `561.75` damage four times every `6.5` seconds plus `3000` damage every `16` seconds, for `533.16` DPS vs medium armour, or `511.56` EDPS
Ions apply `2200` damage every `7` seconds, for `314.3` DPS vs heavy armour, or `183.6` EDPS
HMFs apply `2700` damage twice every `16` seconds, for `337.5` DPS vs heavy armour, or `206.8` EDPS


Using these numbers we can see what we are paying for in terms of time and RUs:

**Every second spent on a DD gives us `1045` HP, `4.68` DPS and `4.49` EDPS
Every second spent on an ion gives us `612` HP, `9.08` DPS and `5.3` EDPS
Every second spent on a HMF gives us `612` HP `9.75` DPS and `5.97` EDPS**

**Every RU spent on a DD gives us `59` HP, `0.27` DPS and `0.26` EDPS
Every RU spent on an ion gives us `30.7` HP, `0.45` DPS and `0.26` EDPS
Every RU spent on an ion gives us `30.7` HP, `0.48` DPS and `0.3` EDPS**

## Implications, additional factors

By the numbers, it seems DDs are offering roughly twice the HP/s while still giving us only slightly lower EDPS numbers. From this, we could say DDs are outstanding units, however we know this isn't true - in practice they require good execution to come out ahead.

### Production queue differences
This is partly because of available production queues - *at most* you can produce two DDs at a time, and to get that second queue requires a shipyard. Conversely, frigates can be built from all production vessels. In practice, its standard for games which develop into the midgame for Hiigarans to have two carriers on the field, and Vaygr to have three.

**The effect of additional queues is a price reduction**, in that you are spending less seconds by a factor of `1 / available_queues`. 

#### Two queues:
Every second spent on DDs gives us `2090` HP, `9.36` DPS and `8.98` EDPS
Every second spent on ions gives us `1224` HP, `18.16` DPS and `10.6` EDPS
Every second spent on HMFs gives us `1224` HP `19.5` DPS and `11.94` EDPS
#### Three queues:
*N/A*
Every second spent on ions gives us `1836` HP, `27.24` DPS and `15.9` EDPS
Every second spent on HMFs gives us `1836` HP `29.25` DPS and `17.91` EDPS
#### Four queues:
*N/A*
Every second spent on ions gives us `2448` HP, `36.32` DPS and `21.2` EDPS
Every second spent on HMFs gives us `2448` HP `39` DPS and `23.88` EDPS

This production flood (called spam by most of us) is what makes HMFs seem to overbearing, rather than any other factor. The easy access to many production queues and improved manufacturing allows Vaygr to reduce the time cost of all their units much faster than other races.

### Sustained Damage vs Glass Cannons

HP compliments EDPS in that a high HP value means the damage is harder to stop. A frigate with 1000 EDPS wouldn't be anything outstanding if it died in one hit. Conversely, a unit with 400,000 HP is nothing more than tedious if it only has 0.1 EDPS.

Destroyers and frigates take different sides on this scale, destroyers favouring tougher armour and lower damage, frigates favouring lower armour and higher damage. This means, if micro'd properly, the EDPS value of destroyers is much harder to reduce, despite being lower overall. Frigates on the other hand can be prevented from applying their damage if they are killed too quickly. In a long fight with high unit counts, the EDPS of a frigate cloud will drop steadily, whereas destroyers will linger for longer and lose damage in more spaced-out chunks.

The issue a destroyer player faces is getting enough destroyers out to the point where they can kill frigates faster than they can be produced - against three or four queues, this can potentially be three or more destroyers. **With kiting and regen, this is absolutely doable**.

Another thing to note: Hgn players have access to defence fields, which *utterly cripple* destroyer EDPS.

### Gameplay

Destroyers face another issue: they can struggle to protect objectives such as carriers and resourcing. This is not only because they are slower than frigates, but because you simply have *less* destroyers. Its not too difficult for a frigate player on the back foot to split his force to snipe refineries or even isolated carriers. In addition to all this, their low damage can often mean the refinery or etc will die before the frigates, even if the frigates would lose 100% of the time to the destroyers.

This means destroyers can be great in a slow-pushing ball of doom, but struggle to keep pace with harassment and/or distributing to multiple locations,

## Conclusion

I'd honestly say both of these buffs together can solidify destroyers in the role they were always *meant* to occupy: a frigate player *should* lose to a destroyer player - its literally their job description to beat frigates.

Having playtested against myself, destroyers are still about toe-to-toe with anti-capital frigate spam.

**Comment by cloaked2222** [comment]
Thats a lotta analysis. DDs main strength is range, same goes for BCs really. You can do so much with a range advantage... That DD game is up on my youtube now btw.

Usually you dont go pure DDs.... You get DD, then ions or DFF from your 1 or 2 CCs. DDs plus DFF is just sick.

We (Hideki, myself and others) vouched for a DD nerf after HWR 1.3/hw2c for very good reasons. It may have been over nerfed by Gearbox in v2.0 (we specified a nerf, Gearbox chose how much). However DDs were brough back up some in 2.205. Have a look at the stats tool to see the changes. Mainly lower upgraded health.

Im open to a significant DD health regen buff (like 2x better), or even a slight weapon buff. But DD build time has been the same since hw2c and should not be changed.

**Comment by Novaras** [comment]
my problem is that dds already work decently enough if you get them out in numbers around 3+, even with two they are a handful, so a built time buff fits the bill without increasing their power signature elsewhere

i guess im open for no build time and regen:
`1074 => 800 (-25%)` for `148.75` HP/s

**Comment by cloaked2222** [comment]
It was 1500 in hw2c. Do 750 for half that.

Vay DD should be done too. Will need to do 10x tests to make sure both ships still mol deathstrike each other.

**Comment by cloaked2222** [comment]
Perfect the matchups are correct.

Uve got a typo in ur first perecnt btw, its -30%

**Comment by Novaras** [comment]
fixed, was 30 in props anyhow
build time reverted, im fairly happy with how this is currently although i would have liked vaygr destroyers to have a slightly different set of matchups rather than just being almost a reskin

**Comment by cloaked2222** [comment]
Hiig DDs should kill colls faster than vay per classic. Vay can kite better and deal with marines better obviously. Hiig can also damage decent vs swarm, etc. Diffs are more subtile.
