### ISSUE TITLE
some ability changes need outlining in prop

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#16]
@cloaked2222 

- hw1 scout speed burst changed (to my changes a while back?)
- gravwell accuracy modifier
- cloak ability stats + mults
- drone frigates ability tweaks
- `NewShipType.collisionMultiplier` means kamikazi damage yes? If not, fix/remove collector entries in tai and kus and hgn props under nerfs
- why were missile destroyers nerfed against hw2 vettes?

clarification in props please, or just explain these to me and ill do it

**Comment by cloaked2222** [comment]
I'll let you update the props for now. Many changes are simply 'to be closer to hw1c'/slight buff/slight nerf.
1. "speed burst ability duration reduced from 50secs to 30secs, and top speed reduced 4%. (was too hard to deny hw1 scouting)" per your suggestion
2. in 2.205 its ability range was lowered from like 3750 to 3000, but gearbox forgot to lower the accuracy modifer sphere too. They are supposed to be the same.
3. Kushan/Taiidan Cloak Generator ability duration increased from 100 to 120sec (to match hw2 races, and be closer to hw1c). slight buff
4. to be like hw1c/slight buff
5. correct. before cheap hw2 colls could take out expensive hw1 colls... I balanced it so 1 hw2 coll takes another down to 10% health. Same for hw1 vs hw1. hw1 can prolly kill a hw2 coll - didn't test but obviously that would be fine.
6. March 8th change log: "Kushan/Taiidan Missile Destroyer damage vs hw1 corvettes down 40% (now performs similar vs hw1 and hw2 corvettes). Kushan/Taiidan Missile Destroyer speed up 12%. (relatively closer to hw1c)"
I botched this testing hard earlier this year... can explain in chat. I lowered its damage vs hw2 corvs some, so it performs similar vs hw1 and hw2 corvs. Feel free to run some tests yourself.
