### ISSUE TITLE
Cross Race Docking Bug

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#19]
.dontDockWithOtherRaceShips
@cloaked2222 

does this mean hgn can't dock with vay, and etc.? Or is this just between HW2 and HW1? Not sure how I feel if the former.

**Comment by cloaked2222** [comment]
Former. Its the best solution available, and I'd much rather have this that the cross race docking bug. Its a huge PIA having to manually select docking targets when you have a hw1 ally. It can also be seen as a minor nerf to hw2's docking regeneration in team games.

**Comment by cloaked2222** [comment]
Echo and I thought of some scenarios that aren't covered by the Cross Race Dock Bug fix. :/ The way HWR works, when you control a ship HWR usually considers it your own race - even if its really another race.

So if HW1 and HW2 are allied, HW2 can transfer ships to HW1. HW1 could then dock squadrons in refineries etc leading to dock bug. :/  Tested and confirmed.

Ship transferring or ship capturing/salvaging may all lead to people running into the Cross Race Dock Bug.

**Comment by Echo1707** [comment]
> So if HW1 and HW2 are allied, HW2 can transfer ships to HW1. HW1 could then dock squadrons in HW1 refineries etc...

You have a typo there: **HW2** could then dock squadrons in HW1 refineries etc...
