### ISSUE TITLE
cruisers dont appear balanced

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#20]
see [this](https://github.com/HW-PlayersPatch/2.3/blob/Cloaked/TestData/hw1%20cruisers%20vs%20hw2%20cruisers.xlsx) data

there may be effects at play im not aware of such as supports hitting engine systems, however overall my conclusion is the healing from supports doesn't outweigh the effects of rng during such a high dps fight (reliably)

occasionally one frigate is enough for a break even, usually it requires three, and sometimes you can still lose with four

hw1 cruisers also cost more and take longer to build, and support frigates aren't free either

**Comment by cloaked2222** [comment]
Total costs are actually in hw1's favor, see:
HWR Core Comparison_2.3 Hgn vs hw1 030918.xlsx
HWR Core Comparison_2.3 Vgr vs hw1 030918.xlsx

The below assumes both sides start outside of range of each other. Generally cruiser fights happen at max range, as kiting micro is involved. Note: If your not already: when testing cruisers in the balance window, don't just press 'start'. Take the ship that's facing the wrong way and turn it around properly. Its unfortunate that they didn't make both sides face the center...

Cruisers were balanced a long time ago so 1 hw2 cruiser vs hw1 HC + support frig comes out even.
-This doesn't mean that the cruisers kill each other and hw1 is left with a free support frigate.
-This means if hw2 kills the support frigate first, the cruisers will come out even. If hw2 just fires on the HC the whole time, when the HC dies the hw2 cruiser will be at low health and hw1 will still have a support frig that they can retreat.
-In actual games, having 4 support frigates healing a HC is extremely powerful. Kiting and saving the HC, allows it to be healed outside of combat - which is huge. hw2 has to sacrifice their economy to do this.

I'm open to discussing changes here if you still feel they are needed.

**Comment by Novaras** [comment]
im quite tired so forgive me if im being stupid here, but that comparison seems bizzare to me; many infastructure costs are ignored for HW1, and even hiign research modules aren't included... i guess the aim was 'BC-specific mods' or 'mods not in every game anyway'? Don't like this arbitrary cherry pick on a hard comparison such as this

in any case here is a real comparison of the costs:
![cruisers](https://user-images.githubusercontent.com/17747768/40909590-d5e0b06a-67e1-11e8-87fd-fbf7fe9318a6.png)

**Comment by cloaked2222** [comment]
The core comparison files are meant to compare a 1v1 build up, that starts with fighters and/or corvs, then progresses to frigates, destroyers, and cruisers.

Obviously hw2 has the flexibility/advantage to just rush to cruisers alone efficiently in larger team games. hw1 can't do this, as they must unlock frigs, and destroyers to get to cruisers.

Yes hw2 can sell off mods in dire situations, or for extreme rushes. However Hiig typically needs to rebuild/keep a research/advanced/hyperspace module for the length of the game. If you do the same comparison for Vaygr, they look much worse with only a 500ru research mod and more expensive BC/capital upgrade research. Selling that is about as useful as recycling a hw1 research ship.

One idea would be to lower hw1 cruiser build time closer to hw2 cruiser build time with imp manu (its 215.4 seconds, not 196). However my concern is that hw1 cruisers would then build too fast compared to hw1 destroyers and ions. And buffing all 3 would be OP.

hw2 base->imp
Ion: 45->34.6
DD:165->126.9
BC:280->215.4

hw1 current->idea
Ion: 70->50
DD: 145->125
HC: 250->215

hw1c:
Ion: 60
DD: 150
HC: 420

If you want to do something, I would instead suggest we buff hw1 ion build time to 60seconds, and possibly buff support frigs.

**Comment by Novaras** [comment]
HW1 capship chassis research with 2 ships is `69s`, current support frigate build time is a whopping `85s`. In general I'd expect it to take roughly the same time to build a support frigate as it would take me to get cap chassis, or another frigate. That's just QOL, and feels natural. After this I'd avoid buffing HW1 anywhere else since v8 contains quite a number of buffs for HW1 already...

support frigates: `85 => 65s (-24%)` or `85 => 70s (-18%)`
assault frigates: `68 => 65s (-4%)`
ion cannon frigates: `73 => 65s (-7%)`

**Comment by cloaked2222** [comment]
Make supports 70 (they were 5sec slower in hw1c). 

Dont buff support health. It was actually weaker than an ion in hw1c. Its currently the same. Buff manuverability properties more or heal rate if necessary. Also plz compare heal rate to hw2 collector healing. Im wondering how it compares. Btw i think sidearmour damage is ignored when healing.

We'll definitely need to do lots of playtesting before a release. With all the changes this week isnt gonna happen.

**Comment by Novaras** [comment]
would rather just lower their HP than have directional armour

**Comment by cloaked2222** [comment]
Sidearmour damage covers 99% of ship other than direct rear. Many ships have this, including most frigs. Ur memory must suck when i tell u this at 4am :p

**Comment by Novaras** [comment]
yeh, but why bother with it

misleading in ui (for whatever its worth) and occasionally inconsistent

**Comment by cloaked2222** [comment]
Update on sidearmour, learn something new every day!

Turns out sideArmourDamage actually covers 98% of the ship. rearArmourDamage covers a 1% cone in the direct rear, and there's a 1% cone in the direct front that receives normal damage!

If you tell two ion frigs to attack each other, they will line up and attack into the front cone. But if you tell an ion frig to attack a carrier head on, it will quickly sway/bob out of the carrier's front cone and start applying sideArmourDamage.

**Comment by cloaked2222** [comment]
Closed. hw1 frig build times are being buffed:
https://github.com/HW-PlayersPatch/2.3/issues/20
