### ISSUE TITLE
Tactics multipliers might need a check

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#21]
These are the tactics multipliers in tai_resourcecollector.ship:
`setTacticsMults(NewShipType, "ENGINEACCEL", 1.05, 0.95, 1.0)`
`setTacticsMults(NewShipType, "THRUSTERACCEL", 1.05, 0.95, 1.0)`
`setTacticsMults(NewShipType, "ROTATION", 0.95, 1.05, 1.0)`
`setTacticsMults(NewShipType, "ROTATIONACCEL", 1.05, 0.95, 1.0)`

Seems like in evasive `ENGINEACCEL`, `THRUSTERACCEL` and `ROTATIONACCEL` are nerfed (or they might be buffed if these mults are used as dividers; for example `FIRERATE` is confirmed to be a divider).

Is it okay to open a wiki that explains what the different `setTacticsMults` actually do and use this thread to discuss what type of bonuses should different ships in aggressive or evasive have?

**Comment by cloaked2222** [comment]
Lower values for many properties are desirable. For example:
Firerate = 10
Firerate = 5 This fires twice as many shots per minute.

While gearbox may have made a few mistakes, mostly these values make sense and your best bet it to test and confirm. Just change the multi to 0.01 and 10.0 to confirm.

Feel free to make a wiki. There's not a great source of info on balance stuff, so your best bet is to test and see, and if your still stumped ask me.

**Comment by cloaked2222** [comment]
Just FYI, it appears gearbox gave many swarm ships a slower "ROTATIONACCEL" in evasive, so they don't turn so sharp. Sharp turns = better chance to get hit by weapons.

**Comment by Echo1707** [comment]
Thanks for the info. How do you think is the current balance between "all aggressive ints" and "some ints/scouts in evasive"? Would it be okay to tune ints/scounts evasive multipliers to be closer to neutral stance?

**Comment by cloaked2222** [comment]
Ya gearbox over did these modifiers. Really no need to even use half of them, especially not 20% damage, +20% penetration type crap resulting in +40% dps... We would need to compile a list of all modifiers, and come up with a design. The design would tell us which multipliers to use on which ship classes, and about how much the multipliers should be by ship class, etc.

Right now i just use Agg for battles, and Ev for docking/running away. Then often forget to change back to Agg... Fear uses them in more interesting ways.

Ideally we'd tune these properly so we can set the default for swarm back to 'Normal'. It would be an absolute ton of work to re-balance all swarm though... Me/fear discussed this before and didn't want to bother. Would prolly be best to look at the formation modifiers instead and try to fix those (wouldn't touch the default ones for hw2 squads though, or again swarm would need to be re-balanced).

**Comment by Echo1707** [comment]
I think HW2 squadrons will thank you if their default stance stays aggressive :)

Taking the Kushan int as an example for what I have in mind, let's say that we are fine with it's current aggressive and evasive speed:

`setTacticsMults(NewShipType, "MAXSPEED", 1.0, 1.10, 1.0)`
`NewShipType.thrusterMaxSpeed=487`
`NewShipType.mainEngineMaxSpeed=487`

This means that we could change the neutral stance to `(1.0+1.10)/2 = 1.05` in order to have the actual neutral stance speed in-between the aggressive and evasive ones (if we want to keep the numbers perfect and show the aggressive stance speed in the unit tooltip), or we could change the values to something like:

`setTacticsMults(NewShipType, "MAXSPEED", 0.9524, 1.0476, 1.0)`
`NewShipType.thrusterMaxSpeed=511.35`
`NewShipType.mainEngineMaxSpeed=511.35`

(to show the neutral stance speed value and to keep neutral stance multipliers at 1.0).

`WEAPONDAMAGE` and `DAMAGEAPPLIED` multiply each other, right? So if the first is 1.2 and the second is 1.1, I could set one of them to `1.2*1.1 = 1.32` and the other to 1.0 and have the same effect.

**Comment by cloaked2222** [comment]
Pie in the sky
