### ISSUE TITLE
Multi-guns

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#22]
Per Fear "multis vs hw1 fighters are busted https://i.imgur.com/8phEFVX.png"

**Comment by cloaked2222** [comment]
The majority of my testing for swarm will have one side at max unit caps. So for multi's i tested 70ints vs 15,18, and 21 multis. In this regard, last month-ish i tuned them somewhat better than the results in "2.3 Players Patch - Swarm Balancing 120217.xlsx". 18multi for example beat 70ints.

I have not done much swarm testing with low numbers of units. 70/18 = 3.9. That might suggest that 2multi's should beat 8ints. But its not that simple. When there are 70 ints in the sky there are tones of targets - so multi's will always be shooting at something. With only 8ints in the sky, they will often be not firing at all.

So feel free to improve multi's in smaller skirmishes, but just remember to test them in larger numbers too.

**Comment by Novaras** [comment]
i've shuffled a lot of numbers as of my latest push, try these out and also check the new data

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/2.3/pull/31

**Comment by cloaked2222** [comment]
Looks a bit better than i had them, but prolly OK. This is fine by me, don't need to see detailed tests.
