### ISSUE TITLE
Abusing Dock Regeneration

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#23]
Me/Fear tested. Its busted vs hw1. Propose making fighters/corvettes take much longer to heal in dock.

My best balance idea ever? Quite possibly.

hw2 carriers and motherships:
addAbility(NewShipType,"ShipHold",1,40,100,"rallypoint","Fighter, Corvette,Utility",35,{Fighter="36"},{Corvette="75"});
Lower the last two numbers as needed. [More info.](http://hw2wiki.net/wiki.hw2.info/FunctionaddAbility_show_comments=1.html). Maybe start with 12 and 25 and see how that feels.

**Comment by Novaras** [comment]
healing rate is quite unusual, most times are either in `1/1` seconds or `1/10` seconds, however this rate seems to be in `1/squadron_count` seconds... setting `Fighter=3` seems to cause a 0% - 100% heal on an interceptor in 6 seconds:
`(squadron_max_hp / squadron_count) / time = repair_value *  squadron_count   = hp_per_second`
`90 / 6 =  3 * 5    = 15`

so to aim this correctly (`squadron_count` is a constant we won't change):
`time = (squadron_max_hp / squadron_count) / (repair_value * squadron_count)`

For ints this currently works out like so:
~~~~
time  = (450 / 5) / (36 * 5)
      = 0.5s
~~~~
For corvettes (base):
~~~~
time = (480 / 3) / (75 * 3)
     = 2.1s
~~~~
For corvettes (upgraded):
~~~~
time = (720 / 3) / (75 * 3)
     = 3.2s
~~~~

### [You can see tables of potential values here.](https://www.desmos.com/calculator/0v0g9acmhf)

Currently I like `Fighter=3` and `Corvette =40`

**Comment by Novaras** [comment]
Implemented changes (54531b2b515d2b40ea714754f9cea5d0cac2b6a7), try them out

**Comment by cloaked2222** [comment]
Make ints 5sec plz. Vettes are fine.

I need to test actual in game times for hiig/vay ints in hw2c. I suspect gearbox's squadron/batch changes may have unintentionally changed these. I also suspect the races may have been asymetrical here.

**Comment by cloaked2222** [comment]
As I suspected gearbox must have messed this up somehow...

hw2c:
Dock a fully upgraded squadron with just one unit left at full health. Repair times while inside the launch manager are listed below:
Hiig Int: 10.5sec
Pulsar: 18sec
Vay AC: 16sec
Missile: 27sec

Please match these same times in HWR. Be sure to do all Hiig/Vay MS/CC/SY/BC. Might want to check out hw1 dock repair times too.

**Comment by cloaked2222** [comment]
https://github.com/HW-PlayersPatch/2.3/commit/b2fe77dcd0c7bff6a7b35f279456c75e7c577e23

**Comment by cloaked2222** [comment]
**More info:**
In hw2c, it took proportionately longer to heal a 1/5 squad than a 4/5 squad. Same goes if you tried to dock 10 squads with 1/5 left at the same time, would take a while to heal them all. hw2c healed each ship one at a time, before moving on to heal the next. HWR v2.0+ dock times are the same whether you have a squad with 1/5 left, or 4/5 left. Same goes if you dock 10 squads with 1/5 left at the same time. HWR will heal each individual unit simultaneously.

Repair times, when docking a fully upgraded ship with 1hp left. Doesn't matter how many squad members are left.
b7:
Hiig Ints: 0.5
Hiig Pulsars: 3.2
Vay AC: 0.36
Vay Missiles: 2.4
Kus Ints: 2.5
Kus Heavies: 22.7

b8:
Hiig Ints: 10.6 (to match hw2c time to regenerate 4 units)
Hiig Pulsars: 18 (to match hw2c time to regenerate 2 units)
Vay AC: 16 ("")
Vay Missiles: 27 ("")
**Kus Ints: perhaps (10.6 / 4) = 2.65
Kus Heavies: perhaps (18 / 2) = 9**

Looking for feedback on the proposed hw1 repair times.

**Comment by Echo1707** [comment]
Mmmh... I have a feeling that in hw1c only fighters were docked for repairs since corvettes can be repaired with repair beams, while both fighters and corvettes were docked when they needed to be refueled. Also HW1 don't gain 4 ints for free when they dock one, so probably it's okay to have fighters heal faster and corvettes heal slower?

**Comment by cloaked2222** [comment]
Implemented:
https://github.com/HW-PlayersPatch/2.3/commit/96fe5f13cdde7fc3b099291ab3225ceb2aa80dd0

Repair corvettes previously only had one base repair value for all ships, set to 12. I've bumped that to 70 to match support frigates, and added the separate values for fighters/corvs.

Also lowered the base repair value on hw1 carriers (200) to match hw1 motherships (100). hw2's base repair value is 35 for reference. The base repair value mainly affects repairing resource collectors.

hw1 and hw2 repair rates are vastly different now:
Vay: ,{Fighter="0.8"},{Corvette="6.7"});
Kus: ,{Fighter="34"},{Corvette="189"});
This means it would take 42 times longer to heal a hw1 fighter in a vaygr ship, and 28 times longer to heal a hw1 corvette in a vaygr ship. Due to this, I also restricted kus/tai ships from docking in other race ships:
https://github.com/HW-PlayersPatch/2.3/commit/410eaa89f770991807998b4fdb1f7eb1407d1af4
Hiig/Vay were already restricted due to the cross race dock bug which causes major lag. So at-least all the races are consistent now.

**Comment by Echo1707** [comment]
Reopening this: please check that all ships repair at thesame rate:
Mothership/(refineries/controllers)/SY vs collectors
HW1: Mothership/carrier/support frig/repair corvette/controller vs ints
HW1: Mothership/carrier/support frig/controller vs corvettes
HW2: BC vs ints/corvettes

**Comment by cloaked2222** [comment]
Great catch!

Collectors repair at the default value, which appears before fighter/corv specific values.
