### ISSUE TITLE
Repair Corvs

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#24]
I did some tests a while ago/somewhat recently:
42 Heavies vs 36 Heavies + 6 Repair corvs
and other combinations like this. Seemed better to not have repair corvs.

I'd love to see this be hw1's answer to hw2 corvette dock healing.

This needs more testing by Fear, and you can buff as/if needed.

**Comment by Novaras** [comment]
non issue, heavy changes and rep changes some commits back mean repairs are strong in corvette fights:

25 h + 5 r vs 30 h: left side wins 11 h remaining
36 h + 6 r vs 42 h: left side wins 20 h remaining

**Comment by cloaked2222** [comment]
So I discovered that the heal multipliers are controlled in the .ship files here:
addAbility(NewShipType,"RepairCommand",1,250,1,1,"Frontal_RepairCorvette",
{Corvette=1.5},

I did many tests between 1.5 and 2.0. Seems you need to set it close to 2.0 to make repair corvs useful in heavy corvette fights. But then it seems like they're OP vs pulsar. -_-

Also not sure what the 'ideal' compositions are, but I was getting 15 heavies + 15 repair corvettes to beat 30 heavies. This can get silly if its better to have more repair corvettes than attacking units. -_-

This needs more attention and a lot of tests.

**Comment by Echo1707** [comment]
Seems like penetration/multiplier values can be defined in the .wepn file too: https://github.com/HW-PlayersPatch/2.3/blob/Bleeding-Edge/2.3_Update/weapon/kus_repairgunheal/kus_repairgunheal.wepn
Line 10: `{ResArmour=0.8});`

**Comment by cloaked2222** [comment]
Ya I did a lot of tests and that surprisingly has no effect. Gotta use the .ship file
