### ISSUE TITLE
Taiidan Support Frigates

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#25]
The top left and bottom right gun always miss small targets like idle probes, and likely fighters, maybe corvs.

2 hardpoints are miss-aligned in the .hod. Both use tai_assaultgun2.wepn

See solutions here under "General Bugs: Miss-Aligned Guns" https://forums.gearboxsoftware.com/t/hwr-bugs-solutions/1639765/1

Also need to make sure this ship is balanced vs kus in all important match-ups.

**Comment by cloaked2222** [comment]
Bug is now properly fixed thanks to Fear stumbling across the 'magic' solution, and cloaked eventually fumbling into the root cause...

Solution:
tai_assaultcannon2.subs
change to:
LoadSharedModel(NewSubSystemType,"Tai_AssaultCannon");

**Comment by Novaras** [comment]
fixed: 170e98548a0b0132cc272f8091279c1e62236773
