### ISSUE TITLE
vs Collectors

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#26]
@cloaked2222 

> hw2c: 20 Hiig Int vs 4 lv2 Hiig colls = 160sec
			Target 120-130 seconds now that full upgrades are easier to get.

Currently takes around `90s` vs lvl2 HW2 colls
Currently takes around `115s` vs HW1 colls

im happy with those numbers, just checking you don't have a major gripe here

**Comment by cloaked2222** [comment]
For a practical hw2c time vs lv1 colls (hiig 400ru for 1.5x health) i estimate 120sec. Ints vs colls struck a good balance in hw2c. Rusher could pick off a couple colls while defender CC guns damaged ints to allow the defender to recover. This delicate balance lead to the "+2 rule". You could generally build 2 more collectors than your opponent and still hold. 

What is time in 2.3 b7? Need to know that before i can advise.

**Comment by Novaras** [comment]
2.3 takes around `153s` vs lvl2 HW2 colls
2.3 takes around `193s` vs HW1 colls

**Comment by Novaras** [comment]
[Data for ints vs colls](https://github.com/HW-PlayersPatch/2.3/blob/Cloaked/TestData/ints%20vs%20colls.xlsx)

[also please note this discovery](https://github.com/HW-PlayersPatch/2.3/issues/29)

**Comment by cloaked2222** [comment]
Data looks fine. U can close this.

**Comment by Novaras** [comment]
[Data for corvettes vs colls](https://github.com/HW-PlayersPatch/2.3/blob/Cloaked/TestData/corvettes%20vs%20colls.xlsx)

ints now with `0.4` pen as discussed previously

**Comment by cloaked2222** [comment]
Going forward, plz compare corvs in equal unit caps: so hw1 9, hiig 9, vay 12. hw2 corvs are cheaper as upgrades must be purchased for them. Same goes with most ships.

Here's some basic target ideas, please tweak and add flavor. Target time for 9x corvs, Best vs, OK vs.
Hiig Gunship: 80, colls, refinery
Hiig Pulsar: 100, refinery, colls
Vay Missile: 80, colls, refinery
Vay Laser: 100, refinery, colls
Light Corvs: 80, colls, refinery
Multi Corvs: ???, colls, refinery
Heavy Corvs: 100, refinery, colls

Pen:
colls = resarmour
refineries = mediumarmour (do not change, impacts frigs)

Accuracy:
colls = Resource
refineries = ResourceLarge (also affects hw1 research ships...)

**Comment by Novaras** [comment]
Dunno if I care about one-time costs enough to change the test numbers, but ok.

My targets would be (ints take `99s`)

`Name: 4x Colls | Refinery | Current refinery (rough)`
`-` = no change
Hgn:
* Gunship: `70 | 120 | 112`
* Pulsars: `90 | - | 54`
Vay
* Missiles: `70(?) | 120 | 160`
* Lasers: `100 | - | 22 (one pass)`
Kus & Tai
* Lights: `65 | 130 | 102`
* Multis: `80 | - | 144`
* Heavies: `90 | - | 38`

**Comment by cloaked2222** [comment]
I tested hw2c, and then tweaked your targets some based on the results.
9 lv2 corvs (12 for vay) Vs 4 colls lv1 (or 1 controller lv1)
4x Colls | Refinery

hw2c:
Gunships: 83 | 284 (3 corvs died)
Pulsar: 73 | 91
Missile: 66 | 116
Laser: 59 | 33

Targets:
Gunships: 80 | 120
Pulsar: 90 | 75
Missile: 70 | 120
Laser: 80 | 35
Lights 70 | 130
Multi: 80 | 140
Heavies: 90 | 55

Also mine-layers feel fine:
hw2c: Hiig Minelayer: 69 | 85
HWR: Hiig Minelayers: 79 | 93

**Comment by Novaras** [comment]
really have no interest in making gunships worse at anything, even after its buffs this unit is still... niche, despite my best efforts

pulsars being worse vs refs mean they would be worse vs frigs too, which im okay with but then again, I'm *very* bias against this unit so ehh, unless you want to buff refinery hp which i won't be any part of

heavy and laser changes also have the same problem

multis being good vs colls pushes lights into a 'why the fuck am i making lights' area, which they might already be in after multi buffs, so need to think about this one

**Comment by cloaked2222** [comment]
I haven't tested gunships vs colls in 2.3, so i dunno b7 time or current time.

You must have missed my edit (gotta wait a bit to read each others posts on here, lol). To get closer to target refinery times, lower accuracy vs ResourceLarge some - its currently at 100% for most ships. It could go as low as 65% if needed. Don't mess with frig pen.

Multi can be a bit worse vs colls, i just edited my post for this idea.

**Comment by Echo1707** [comment]
I don't particularly like, as HW1, having 1 corvette good vs collectors and ok vs fighters (LCv), 1 corvette good vs frigates and ok vs corvettes (HCv), 1 corvette good vs fighters (MCv) and 1 corvette for repairing the 3 above (RCv), expecially when Vaygr missile corvettes are anti-fighters (?), anti-corvettes and anti-collectors.

Maybe lights should be really great against collectors (but less good against fighters), multiguns vs fighters and heavies good vs both corvettes and frigates?

This is a treasure-trove: https://www.youtube.com/playlist?list=PLUmlduw0Zc37KPppOLdYbJgiCGvoDAp6I
I don't know how many of these matches are between skilled players, but maybe we can get a feel of how lights and multiguns performed compared to heavy :)

**Comment by Novaras** [comment]
Vaygr only have two combat vette classes to  work with, hw1 has three... Probably want to curb missiles rather than buff hw1 vettes. They were massively overperforming vs collectors, dunno about now. Vaygr also have to construct modules and upgrade their units, so having them a little more generic is probably fine too. I'd rather see how current v8 feels rather than change a whole unit class which has already been changed a bunch

Just opinions

**Comment by Echo1707** [comment]
Reopening this issue to include ints/bombers/cloaked fighters/HW1 Assault/Improved torps/Vay Assault times vs colls and refineries. Will update with data as soon as I do the tests.

**Comment by cloaked2222** [comment]
I did test all those units vs colls (not refineries) right before I closed the issue. Several were tweaked as needed, so they should all be good.


Check the BalanceInfo/Stats Tool/b7 vs b8 (something like that), to see which weapon penetration values vs colls changed between b7 and b8. Remember upgraded collector health also went down from b7 to b8.

________________________________

**Comment by Echo1707** [comment]
Someone one Discord said that ships weren't damaging collectors fast enough, and since the topic was only about corvettes, I figured I'd check them. Since I already did a few tests, I'm just going to post the results. Feel free to close the issue ^^

Tech: all engine upgrades and improved torps (no improved bombs and no armor upgrade)
Conditions: default stance, bandbox (no micro), collectors and refineries not moving
Time vs: 4 hig colls | 1 hig ref

15 Hig ints: 96 | refinery wins in 150 seconds with 2/3 or 3/4 health
15 Hig bombers: 50 (1 bomber down friendly fire lol) | 16 (1 bomber down)
1 torp: 60 | 94
1 Hig ion: 165 | 57
1 Marine: can't capture colls | 30 (since the blue beam is emitted)
1 Hig DD: 22 | 27
