### ISSUE TITLE
Tactical Overlay: Defense Fighter, etc

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#33]
A bit much to look at (not in my opinion, but others seem less impressed):

![image](https://user-images.githubusercontent.com/17747768/41485757-b79273d6-70d9-11e8-98d8-166e591a184c.png)

Even without the (grudgingly optional) inner TO for the shield, the standard modifiers are still a lot to look at... I've come up with a solution which produces less obtrusive results:

![image](https://user-images.githubusercontent.com/17747768/41486091-0494efdc-70db-11e8-8a21-4c3058a80124.png)
![image](https://user-images.githubusercontent.com/17747768/41486994-ac20dbfa-70de-11e8-8644-74ec920c15c8.png)

However the method used to attain this translucence is pretty hacky.

I've set *all current in-use modifiers to invisible*, and am using the unused modifiers for styling purposes:

~~~
-- these multipliers are functional and in use, set them transparent
	
	-- used by ecm probes, also found in vaygr hyperspace gates although unused
	SensorDistortion = 
	{
		colour = {1,1,1,0},
	},
	-- used by all fire control, cmd vettes and also by taiidan field frigs and fighters
	WeaponAccuracy = 
	{
		colour = {1,0.48,0,0},
	},
	-- used by all fire control, cmd vettes and also by taiidan field frigs and fighters
	WeaponDamage =
	{
		colour = {1,0,0,0},
	},
	-- used by taiidan field fighters
	MaxSpeed = 
	{
		colour = {0.1,0.85,0,0},
	},
	
	
-- these multipliers are unused and have no users, use them for styling
	
	-- using this to display sensor distortion effect (solid white)
	ResourceCollectionRate = 
	{
		colour = {1,1,1,1},
	},
	-- using this to display taiidan defense shields (translucent neon blue)
	NebulaSensitivity =
	{
		colour = {0,1,1,0.2},
	},
	-- using this to display fire control for all hw2 fire control fields (solid red)
	BuildSpeed =
	{
		colour = {1,0,0,1}
	},
	-- using this to display taiidan debuff fields from field frigates, using orange as weapon accuracy is considered the primary effect (solid orange)
	HyperSpaceAbortDamage =
	{
		colour = {1,0.48,0,1},
	},
	-- using this to display taiidan debuff fields from def fighters, using orange as weapon accuracy is considered the primary effect (translucent orange)
	Capture =
	{
		colour = {1,0.48,0,0.4},
	},
~~~

You can see a working version of all this in the [TO-hack](https://github.com/HW-PlayersPatch/2.3/tree/TO-hack) branch... everything displays as it always has, however we can now apply custom colours to TOs so long as we have spare unused modifiers lying around

The main issue here is that 2.3 will potentially not play nicely with other mods which use these modifiers...

**Comment by cloaked2222** [comment]
"The main issue here is that 2.3 will potentially not play nicely with other mods which use these modifiers..."
Currently 2.3 b8 should be compatible with any mod, so that's definitely a negative. You can load 2.3, then load a mod on top of it and it should always work. That said, for the bigger mods that touch tones of files - you won't see many benefits by doing this. While we may fix a bug in a file, the mod may have its own file that overwrites it. The main goal is for other mods to eventually take advantage of the fixes/improvements in 2.3 by merging them into their mods.

Also maybe black rings would be less noticeable.

**Comment by cloaked2222** [comment]
Impressive stuff. Lets keep in the TO-hack branch for now though.

For b8, I'd suggest removing the neon blue ring around DF and FF. Hiig DFF don't have this and its easy enough to see the shields, this is just UI clutter. Then we can just show the accuracy debuff's with the standard orange.

**Comment by cloaked2222** [comment]
-_- Didn't see it in your OP, and assumed you listed them all. Just now stopped to think and remember 'of course it has a TO ring...'. Its 6am here...

How about this then?
DFF: Stays the same.
FF: Blue field ring, orange -FCT ring.
DF: No blue field ring, orange -FCT ring. Blue ring is helpfull for DFF and FF so you can move other ships inside the ring. Its not needed for DF, as you can't move anything inside those tiny fields.

Then you could just update the standard accuracy orange color as desired, maybe make it more transparent.

**Comment by Echo1707** [comment]
Wouldn't defense fighters die too fast if they were set in passive and ordered to stay still? Also, would it be possible to improve the animation/visual of their field bubble?

**Comment by cloaked2222** [comment]
Ya they sure would echo.

You can modify effects, see here:
https://forums.gearboxsoftware.com/t/modding-tutorials-master-thread/694826/40

@Novaras - I tried to run TO HACK and crashed while loading a game as Hiig. Here's the hwrm.log:
HOD Trace: data:SubSystem\HGN_MS_MODULE_RESEARCHADVANCED\HGN_MS_MODULE_RESEARCHADVANCED.hod 
 HOD Trace: data:SubSystem\HGN_C_MODULE_HYPERSPACE\HGN_C_MODULE_HYPERSPACE.hod 
 LUA 'data:ui/modifiers.lua' -- parameter: <statement> expected;
  last token read: `=' at line 9 in string "" 
 LUA -- incorrect use of PushTable/PopTable -- FATAL EXIT -- luaconfig/1000:! --stack trace--         
 Display: (0, 0, 100, 100) - (8, 31) 
 
Be sure to always use "-traceHODs -luatrace" in your command line when developing.

**Comment by Novaras** [comment]
actually its working on my end... somehow i mustve pushed to remote before testing, tested, fixed, and not pushed again

im usually doing stuff like this late at night so...

**Comment by cloaked2222** [comment]
Fear, plz mark this as b8 or b9 as you feel fit.
