### ISSUE TITLE
SP: Turanic Missile Corvettes

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#35]
Per echo7: "What do you think about increasing the penetration of Turanic missile corvettes vs frigates? ..."

2.3 b7:
21 Tur_Missile Corvettes vs 2 Kus Ion Frigs = 138sec
21 Kushan Heavy Corvettes vs 2 Kus Ion Frigs = 61sec

**Comment by cloaked2222** [comment]
SP ships are mol just 'in the game', and were never well balanced. Some of the worst offenders (like kadeshi swarmers) have been fixed up, but there is much work to do here if anyone wants do dive into campaign balancing tuning.

Ships need to stay true to hw1c: http://well-of-souls.com/homeworld/turanic/index.html
I believe Turanic missile corvettes are anti-fighter and corvette. They aren't meant to be anti-frigate.

echo7 - regarding your PM. The formula's for DPS are complex (there are multiple depending on variables i believe), and I'm not sure they're documented anywhere. I know two people that are good with them, (a dev, and a mod author) however I've seen both make mistakes and even then often in-game performance turns out differently. So its best to test in game.

**Comment by Echo1707** [comment]
Let's also remember that in b8 Kushan Heavy Corvettes are going to perform better vs Frigs and that Assault Frigs are going to perform better vs Corvettes (Turanics' included).

**HW1C M02**
Start of mission: `1 salvette, 1 collector, 1 research ship, 577 RU`
2393 RU harvestable in HW1C M02 ---> `577 + 2393 = 2970 RU`
3 salvettes, 4 repair vettes ---> `2970 - 3*220 - 4*150 = 1710 RU`
`1710/240 = 7 heavy vettes, 30 RU`
Theoretical end of M02: `4 salvettes, 4 repair vettes, 7 heavy vettes, 1 collector, 1 research ship, 30 RU`

**HW1RM M02**
Start of mission: `1 salvette, 2 collectors, 1 research ship, 1591 RU`
6915 RU harvestable in HW1RM M02 ---> `1591 + 6915 = 8506 RU`
Corvette drive research, Corvette chassis research, Heavy corvette upgrade research, 3 salvettes, 4 repair vettes ---> `8506 - 300 - 400 - 500 - 3*250 - 4*175 = 5856 RU`
`5856/240 = 24 heavy vettes, 96 RU`
Theoretical end of M02: `4 salvettes, 4 repair vettes, 24 heavy vettes, 2 collectors, 1 research ship, 96 RU`

**Comment by Echo1707** [comment]
Captured Turanic missile corvettes' missiles are missing asteroids on M06 "Diamond Shoals".

I'm taking this opportunity to tell you guys that I'm getting very busy in RL, so I'll not be able to mod/test much :(

**Comment by cloaked2222** [comment]
Hrm, I'd check the AttackFamily of the asteroids. Then make sure its in the Turanic missile corvette's .ship CanAttack, and also in their .wepn file(s).

Np, we all get busy. =)

**Comment by cloaked2222** [comment]
Pie in the sky
