### ISSUE TITLE
Being able to play the current state of v8 between ourselves

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#37]
Making a private workshop mod for current b8 would allow us to make internal tests. The drawback is that it should be updated after every commit.
Another way would be to use Hamachi or something like it, but I don't know if the files in the referenced mod path must be the same between all players (it could be a problem if we modified something locally).

**Comment by cloaked2222** [comment]
This already exists.

I just informed Fear. He'll be making a wiki on this later.
