### ISSUE TITLE
Observer race, infinite vision range and random races

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#38]
Some players use random races to have an element of surprise vs their opponents. If the spectator is on the opposite team (the spectator should be in one of the playing teams to have a color difference to tell teams apart), and this ship has a lot of visual range, this is what happens:

![homeworldrm 2018-06-16 21-58-04-32](https://user-images.githubusercontent.com/39770560/41502043-e8a09c96-71b0-11e8-83d0-3fd0061079ea.png)

![homeworldrm 2018-06-16 21-59-28-84](https://user-images.githubusercontent.com/39770560/41502045-ed024dd4-71b0-11e8-925e-8261b21a05dd.png)

It should probably be best if it hand't vision range at all.

**Comment by cloaked2222** [comment]
Hahahahah. Great catch.

Someone please set the vision range of this to 10k.

**Comment by Novaras** [comment]
Can Observer race be chosen if you pick Random?

**Comment by cloaked2222** [comment]
No.

**Comment by Echo1707** [comment]
Closing per #49
