### ISSUE TITLE
Resources folder

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#45]
Recently a Resources folder was added to Cloaked's branch. It contains some .zip compressed folders and a link.

`Customized Gearbox Balance Window.zip`: need info about this.

`hw1c Stats`: this is an internet link to [Homeworld Shipyards](http://well-of-souls.com/homeworld/). I know the stats are taken from the 3 classic games (Homeworld, Homeworld Cataclysm and Homeworld 2), but I'm unsure about how much of the text for ship description is canon and how much is fanon.

`Mission Persist Files.zip`: contains data about starting fleets in campaign missions; I'm not sure if this is intended as a default to test mission difficulty or just as a reference (different people have different skill levels and make different build choices); to unzip into `HomeworldRM\Bin\Profiles`

`Starting Fleets.zip`: used for testing in LAN matches against oneself, files can be tweaked however one pleases; folder structure must look like `HomeworldRM\Data\scripts\startingfleets`; best used in conjunction with build costs and build times set to 1, completed research, RU injunction, etc. to speed things up; a link must be created with `-startFleet 1` to activate the custom starting fleet and `-overridebigfile` to apply the build time and cost changes.

`Testing Maps.zip`: maps for testing; might use more info about this if there is any; to unzip into `HomeworldRM\Data\leveldata\multiplayer` so that `Clo_Maps.levels` is into `multiplayer` and the maps themselves are into `multiplayer\deathmatch`

**Comment by cloaked2222** [comment]
Fear can provide info on the balance window. The .zip file is my customized version of it, which takes up less screen space and has some different buttons.

The Shipyards are a reliable source that was used by many people. It was actually hosted on relicnews.com (Relic's old forums) before they were taken offline in 2016. I can't say its 100% correct, but its pretty dam good and the best source around afaik.

Just use your own persist files, unless your missing some or have problems with yours from 2015 like I did.

Good info on starting fleets.

Use the combatpark map for the balance window. Fear can give you more info or create a wiki.

**Comment by cloaked2222** [comment]
The customized balance window files go here:
Data\ui\newui\developer

You can pick from two customized options:
1. gamebalancescreen_spawnmenu - CloakedCustom
->Custom buttons, and takes up less screen space.
The buttons are customized.
2. gamebalancescreen_spawnmenu - CloakedCustomOnlyFormattingChanges
->Just takes up less screen space.

Whatever you want to use, just replace the actual "gamebalancescreen_spawnmenu.lua"

You don't have to use these, but they are a bit nicer. They also start in the far top left by default, which is out of the way more.

**Comment by Echo1707** [comment]
You mean, _rename_ `gamebalancescreen_spawnmenu - CloakedCustom.lua` or `gamebalancescreen_spawnmenu - CloakedCustomOnlyFormattingChanges.lua` with `gamebalancescreen_spawnmenu.lua`? I can't locate any `gamebalancescreen_spawnmenu.lua` to be replaced... But it seems to me that the window is as much top left as it can be. And I need to start with `-balance -overridebigfile -moddatapath` command lines and copy-paste the current 2.3 Bleeding-Edge to actually test the current version.

**Comment by cloaked2222** [comment]
Ya copy one of those 2 fines and rename it to "gamebalancescreen_spawnmenu.lua"

It can go a bit more to the top left =P When ur running 1600x900, every mm counts!

Ooo -moddatapath! I haven't used that before, that's nice.
File path: HomeworldRM\Data\Data2.3PlayersPatch
Command line: -moddatapath Data2.3PlayersPatch

**Comment by Echo1707** [comment]
Ah, now I'm getting this error when I try to start the game with a link:

---------------------------
Steam Error
---------------------------
Application load error V:0000065432

**Comment by cloaked2222** [comment]
You can't start the beta from a custom link. Only works from clicking play in steam library. Unfortunately this means you can't launch the beta twice. :/

**Comment by Echo1707** [comment]
I edited my comment above because it is working via steam, so I just edited the command line there. The error I get is:

---------------------------
Steam Error
---------------------------
Application load error V:0000065432
---------------------------
OK   
---------------------------

**Comment by cloaked2222** [comment]
Looks like the bottom is getting cut off on the customized versions. Here's how the last option looks for me:
![image](https://user-images.githubusercontent.com/18016573/41813602-f7eb7a44-7706-11e8-81d9-2260d09f566a.png)

I'm on 1600x900 and have these settings:
![image](https://user-images.githubusercontent.com/18016573/41813609-282be3d8-7707-11e8-88a7-ad565e171620.png)

You may need to tweak the .lua file so the bottom isn't cut off for you.

Swapsides does not work AFAIK. AI DEBUG likely doesn't either.

There's also a -developer command line, but i forget if it works in this version, or just some older pre-v2.0 dev versions I have.

**Comment by Echo1707** [comment]
Is there a way to spawn a set number of units other than smahing the P1 or P2 keys? I'd like to play with Kadeshi swarmers at elast once in my life without loosing the left mouse button for it :P
And also if I accidentally spawn one more unit for the enemy, how do I remove it?
And if I want to use repair ships? The "Fight" key will make them shoot their peashoter turrets, not their repair beams :/

**Comment by cloaked2222** [comment]
See my edit. You'd have to nuke all the units on the left/right side. No way to nuke just 1 unit on cpu side.

You can't micro the cpu side, so no way to test some things. For that you'd need to run the regular HWR 2x, and play vs yourself on lan.

**Comment by cloaked2222** [comment]
FYI, if your local Git setup isn't optimized here's how to do it:

- Before: C:\Git\2.3
- After: C:\Program Files (x86)\Steam\steamapps\common\Homeworld Remastered Patch Beta\HomeworldRM\Git\2.3

Now I just pull, and play the latest changes. Without having to copy them into my HWR directory. Using this in my command line to play:
-moddatapath Git\2.3\2.3_Update

**Comment by Echo1707** [comment]
Thanks for the suggestion, but I have it already set up for the public Homeworld (that's where I did all my local changes so far) ^^
