### ISSUE TITLE
frigates and corvettes

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#47]
I'm currently tweaking assaults again, and I don't know how I feel about this MU anymore.

Currently I've narrowed the heavy vette / assault frigate matchup to an almost 50/50 in an unmicroed fight... however with basic kiting micro the assaults with *without a single loss*.

So I'm wondering if heavies should win an unmicroed fight every time? Or not? Is there another angle I didn't consider? I can imagine corvettes pushing frigates off an RU patch and turning to gun the colls down, but I can also imagine the frigate player hardly caring since they didn't just throw thousands of rus down the drain and all their units are still alive ready to be healed up....

Right now you could compare this to frigates against destroyers; it takes around 6-7 HMFs to down a DD, and they do this well. However a kiting DD, especially if its partnered up, will perform *significantly* better... So I'm thinking corvettes should have the same type of matchup?

**Comment by cloaked2222** [comment]
My next commit aligns with the targets above, only lasers are doing better vs assault frigates now.

Its rare to spam 14 torps/assaults, generally the most you get are 8, and typically more like 4-6. These matchup's lean towards frigs, as torps/assults allow a player to stabilize if the dice roll unfavorably and you lose swarm hard. Generally mid game, there's going to be ions/dds around that prevent players from getting so many torps/assaults. Corvettes advantage over these units are their speed and mobility.
