### ISSUE TITLE
multigun projectile speed mismatch

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#5]
kushan speed is at `1500`, taiidan is at `1700` - taii multis should be noticeably superior because of this (in current 2.3)

i've nerfed taii speed in the update, however this needs testing

**Comment by cloaked2222** [comment]
Its implemented, and its fine. Just an oversight by gearbox.

**Comment by Novaras** [comment]
issue is obsolete as of a02568c7e88aa6374e020814971d2cb91f002e45
