### ISSUE TITLE
Hiig/Vaygr Review

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#50]
I reviewed all Hiig/Vay research and ship file changes on github for the first time today, and made the following tweaks in the cloaked branch.

Research:
- >Removed minor hiig minelayer cost/time changes. The ship itself is dropping to 400ru instead, as hw1's are 275ru.
- >Removed hiig refinery upgrade change. Refineries pop fast enough as it is to corvs/frigs. Don't need to nerf the upgrade. This would also un-balance Hiig/Vay utility upgrades.
- >Removed Vaygr scout EMP upgrade change. The price matches hiig, and was already nerfed over hw2c, which was 1k.
- >Removed vay carrier buildspeed upgrade change. The price matches hiig, and we have other vay nerfs going in b8. Its a good idea, so maybe build 9 vay (and maybe hiig) can go to 2k.

Ships:

- >Updated all hiig/vay dock repair times, added missing SYs.
- >Further improved DFF rotation speed to match Hiig Ions which were buffed in 2.0.
- >Restored the default stance/ROE design to all ships other than colls (most important) and swarm (so AI don't suck).
- >Removed auto-regen from minelayers and cmd corv. No swarm ship auto regenerates health by design, these ships must be docked to heal.
- >Removed some minelayer buffs, and buffed cost to 400 instead. This better aligns with hw1 cost at 275.
- >Removed controller cost increase. hw1 refineries cost a bit more, partially due to 2 reasons. First hw2 refineries have upgrade costs. Secondly hw1 has a cheaper path to hyper-spacing their MS/CC to their opponents base for very aggressive rushes. hw1 can also stay docked and hw2 will have no idea what it needs to counter such a move. This was OP before v2.0.
- >hw2 scouts get 1k more visual range, as they must built in a squad of 3 which costs more to scout than hw1 races. Makes sense that 3 scouts would triangulate their sensors for a bit better coverage. hw1c scouts had much worse visual range than hw2c scouts did too.
- >Hyp Gates, removed some minor buffs. Buffed build time to 20 sec (orig 45, other plats are 20). Hyperspace gates can now be HYPERSPACED INTO LOCATION FOR FREE!!!! 3 years of thinking of buffs for this ship, and finally something real. =D The time to get these and set them up is their biggest problem.

I'll review weapons later.

**Comment by Novaras** [comment]
vay aren't nerfed very much at all now you've vetoed both of these changes

really of all the changes i proposed for vaygr, the carrier upgrade was the only one i truly thought was necessary (and the collector one)

free gate jumping makes me uneasy... vaygr will be *unbelievably* mobile with a small network of gates. No clue if this will be overbearing or not, can't call it right now i guess

**Comment by cloaked2222** [comment]
Vay resourcing nerf is big. Would like to try that first, then do imp carrier in b9 if needed - its definitely a solid idea.

EMP should be less effective once we hopefully address the '~1hp while not moving' problem:
https://github.com/HW-PlayersPatch/2.3/issues/40#issuecomment-398264147

We can make jumping gates cost ru, perhaps: 100ru base, 200ru max. This will add up if you want a network. This will also make it possible to setup 4 gates in-order to jump twice to get behind a GW. Still seems worse than a nydus worm though, so i don't get the feeling we're over-buffing yet.

**Comment by cloaked2222** [comment]
In reply to this post: https://github.com/HW-PlayersPatch/2.3/issues/51#issuecomment-399781630

Fear: "I'm also surpised at how ready you are to overhaul the entire cast for HW1 but are afraid the vaygr imp. upgrade cost would be too much for a single release"
I'm very touchy with my hw2. ;) Before I got github setup I was planning a 4% ru capacity nerf, while you were separately planning a 500ru emp and 500ru cc imp upgrade nerf. The ru nerf is bigger, and simply undoes a gearbox 2.0 over-buff, so lets start there, and save the cc imp idea for later if need be. We can do it now if you think its really needed on top of the harvesting nerf though. Just don't want to over-nerf and have to back out changes. Regarding hw2 vs hw1, I also feel like hw1 needs much faster carriers though and that means research changes, not just cc build time changes. See the HW1 Research Costs/Times thread I just made.

Fear: "... and other alsmot trivial changes such as two extra movespeed on motherships... the only mission where the MS needs to move at all is the one where it moves in range of some relic, and its speed is manually set in that mission."
Good to know, I'm in the dark on the campaign having not played the hw2 campaign in 15 years. The kus/hiig MS are core to the campaign, and cut-scene type stuff so I'm just leary of breaking the campaign which is very sensitive. Hiig/vay MS can go to 42 or 43 speed now that you've confirmed it wont harm the campaign. Also just remembered we can set stats differently for SP than MP.... rofl, i'll take care of this.

Cloaked: "hw2 scouts get 1k more visual range, as they must built in a squad of 3 which costs more to scout than hw1 races. Makes sense that 3 scouts would triangulate their sensors for a bit better coverage. hw1 classic scouts had much worse visual range than hw2 scouts did too."
Fear: "Why did you rebuff HW2 scouts? Your perception that they are somehow worse than hw1 scouts is confusing at best honestly, the main abuse of scouts is a circle waypoint (so it repeats), not running away and then coming back."
Obviously hw2 scouts are better than hw1 scouts. I simply nerfed hw2 sensors a bit less than kus/tai scout sensors over b7:
b7:
Probes: 100ru, 12k primary sensor, 12k secondary sensor
hw2 Scout: 300ru, 9k primary sensor, 11k secondary sensor
hw1 Scout: 70ru, 9k primary sensor, 11k secondary sensor

WIP Cloaked branch:
hw2 Scout: 300ru, 7.5k primary sensor, 9k secondary sensor
hw1 Scout: 70ru, 6.5k primary sensor, 8k secondary sensor

We can make hw2 7k and 8.5k if you'd like.

**Comment by Novaras** [comment]
I would avoid jumping gates themselves, nydus worms exist in the context of sc2 where other races have things like warp prisms / gates, medivacs etc.

They also have the condition that you can only create a worm in a place you have vision

I'm fine for many of your changes to be attempted in v9 but for now let's try buffing instead of reworking

**Comment by cloaked2222** [comment]
Ya I agree. After thinking on this idea a couple days, I came to the same conclusion. I'll remove it now.

**Comment by cloaked2222** [comment]
Fear, I missed a minor change in the OP:
hyperspace plats regentime/minRegenTime, b7=1200/450, Fear=210/210, Cloaked=450/450
Looking in the stats tool the fastest regentime is vaygr frigs and resource controllers at 1200. Seemed out of place, so I set it to 450 instead to at-least match its original minregentime.
