### ISSUE TITLE
HW1 SP Kadeshi MS

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#52]
In HW1C, the Kadeshi motherships could ram themselves into the player frigates, instakilling whatever they found on their path.

https://www.youtube.com/watch?v=sQ1c_c_zGrE @11:40

It might be fine to increase their frontal ion cannon damage for build 9.

**Comment by cloaked2222** [comment]
Sure. Any campaign improvements are very welcome.

How did you find that video btw? Seems its an unlisted url, as I only see cataclysm's video's on alpha's youtube page. Alpha1SLS helped out with v2.0 early on btw. =)

**Comment by Echo1707** [comment]
When you visit Alpha1SLS channel, hit the "Uploads" button highlighted in red:

![immagine](https://user-images.githubusercontent.com/39770560/41813340-6093a6d4-7734-11e8-89aa-0508c60b7596.png)

And it will make you land on this page: https://www.youtube.com/user/Alpha1SLS/videos?sort=dd&shelf_id=0&view=0

If you still can't access that link or see all his videos, here is a direct link for a default playlist that has all his uploaded videos (first is most recent, last is the first uploaded): https://www.youtube.com/watch?v=zy5iXRLqwm4&list=UUISUDy1-Ko2tPCG427Trm8g

If it still doesn't work, I can download the videos and upload them to Dropbox or something for you to download.

Out of curiosity, did PPOR help too? I never had a chance to exchange words with PPOR or Kadeshi, nor I know much about them (PPOR I saw only in videos and if I'm not mistaken he is/was one of the best HW1 players; Kadeshi I already know it helped balancing HW1 races with Gearbox, but it's a long time since he was last online in the Gearbox forums), yet I miss them even without ever playing/talking with them.

I wasn't aware of that player/channel. It's very recent too! Thanks.

I know Dreamlands is making a campaign walkthrough. I've been providing feedback for some of his videos in private DM... and I was the one who told him that HW1RM didn't have autocollect. I didn't realize it had autocollect untill someone commented on his channel and then I doublechecked it :/

**Comment by cloaked2222** [comment]
-_- thanks found em. He's got the old youtube landing page or something, I just tried clicking the Arrow button on the right, and it only listed the cata vids....

PPOR did not, but he was one of the best hw1 players pre 2.0. Unfortunately 2.0 was such a balance mess that many of the skilled ppl left the game after its release. =/

**Comment by Novaras** [comment]
That mission has a ton of issues in general iirc, I also think the kad ms's attack script should be looked at... Try having fights with them with balance window (this could be fixed by cloaked's ROE changes). Turn speed seems really low... I'm going off very distant memory here but aren't they supposed to be reasonably nimble?

**Comment by Echo1707** [comment]
In the Homeworld Splendor mod there is no reference about a change in speed or turning rate of the Kadeshi mothership, so I went ahead and made this recording: https://vimeo.com/277700832

Stats from HW1C:
Kush Destroyer: 315 m/s
Kush Ion Cannon Frigate and Carrier: 300 m/s
Kush Heavy Cruiser: 250 m/s
Kadeshi MS: 150 m/s

**Comment by cloaked2222** [comment]
Pie in the sky
