### ISSUE TITLE
Mine Duration

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#63]
2.0 Patch Change: "Mine duration increased from 3 minutes to 10 minutes"

I propose we undo this. Me/Fear like mines when used aggressively, or to harass collectors. They should not be a 'you can't attack this location for the next 10+minutes' unit. hw2c was 3 mins fyi.

**Comment by Echo1707** [comment]
Ints can reliably clear minefields (although I think not many people know this).

I'll try to convince a HW1C CPU to cooperate in testing how much time mines lasted and how much damage they did (no reference to minelayers in the Homeworld Splendor mod changelog). I'll report back with a video if I'm fortunate.

**Comment by cloaked2222** [comment]
Unfortunately the internal development forum was on steam in 2015, and does not have a search function. So I can't easily find the hairbrain logic that I may have been a part of... Basically tho, we were looking to buff minelayers in general. Health got buffed per me/hideki, and then mine duration also got buffed possibly per scole.

Here's a public post I made back in early 2015 on underpowered hw2 ships:
https://forums.gearboxsoftware.com/t/underpowered-ships-in-hwr-hw2/263701/1
Skilled hw2 comments are by me/hideki. Skilled hw1 comments are by ratamaq and BlueHair. Ratamaq helped gbx a lot early on in 2015 with the HW1 races.

When your opponent is camping behind a minefield that lasts 10minutes, ints being able to kill mines is about as useful as bombers being able to snipe cruiser modules. Its unlikely to work without losing all your swarm vs a camper.

I'd be ok with 5mins too. 10mins is just such a campers dream...

**Comment by Novaras** [comment]
We can try 5 mins, 3-4 seems high enough to me though

**Comment by cloaked2222** [comment]
Hilarious. I just tested and mine duration in v2.1 is still 3minutes and 20seconds, just like hw2c...

"Mine duration increased from 3 minutes to 10 minutes" This was part of the GBX Balance Mod, which apparently we eventually removed for v2.0:
https://forums.gearboxsoftware.com/t/official-homeworld-balance-mod/552219/1

Sorry guys, brain fart. -_-
