### ISSUE TITLE
Sensors Array

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#64]
Seems like no one ever builds these. Its currently an expensive probe, with the hw2 ping ability.

Primary Sensors/Secondary Sensors range:
Probes: 12k / 12k
Sensors Array: 12k / 17k
Hiig MS with sensors module: 13k / 17k
Secondary sensors show capital ships through the fog of war btw.

- Its primary sensors range could prolly go up to 15k
- Its secondary sensors range can prolly go up. Can echo check its hw1c range? It may have covered the whole map...
- Did this ship have any other hw1c abilities I'm forgetting, echo?
- We could also potentially give it hyperspace sensors, which is something only hw2 has atm i think. See here: https://forums.gearboxsoftware.com/t/hyperspace-sensors/1385617/2
Other mods have done this.
- If we buffed everything appropriately, ping (hw2c only ability) could potentially be removed.

Just ideas at this point.

**Comment by Novaras** [comment]
Everyone should probably have access to ping somehow, should be kept unless this ship will now reveal all units passively like I remember it used to in the hw1c campaign

**Comment by cloaked2222** [comment]
Ya that's fair. Vaygr didn't have ping in hw2c, and that suuuuuuucked.

Back pos to back pos: Fallenlords=40k, CrimsonsBond=60k

Per Echo's SP review, secondary sensors is 100k in the campaign, which will reveal all capital ships. What are you guy's thoughts on this for MP? 100k may be OP, but seems like we could at-least buff it to 20k.

**Comment by cloaked2222** [comment]
Made some minor changes to this unit for b8, see the change log.

Eventually would be cool to give this unit hyperspace sensors, but its more work that I want to bother with any time soon.
