### ISSUE TITLE
Ship Hold Docking Slots

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#65]
I made a survey of all Kushan ships that can be docked with the MS, and I found that minelayer corvette and collectors take 1 docking slot each, all fighters take 2 each and all other corvettes take 3 each. Should minelayers and collectors take more space?

**Comment by cloaked2222** [comment]
.ship holdSlots was added for the 2.0 patch, and was likely quickly implemented. Scole made fighters 2 slots and most corvs 3 slots. Not all ships have it, thus they default to 1 slot.

However ships have plenty of docking space for MP, dunno about SP tho.

I wonder how the current setup compares to hw1c and hw2c.

**Comment by cloaked2222** [comment]
Pie in the sky
