### ISSUE TITLE
Target Priorities

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#67]
Cloaked "Just realized all ships in the game will prioritize attacking hw2 fighters/corvs over hw1... -_-"
Echo: "Not if we give HW1 units a higher target priority for HW1 families ;) For example, HW2 ints focus HW2 ints first and then HW1 ints, while HW1 ints focus first HW1 ints and then HW2 ints, and so on."

**Comment by Echo1707** [comment]
Found this in `kus_heavycorvette.ship` attack priorities:
`"Frigate, Fighter, Fighter_hw1, Corvette, Corvette_hw1, Resource,,,,,,, Capturer, Utility, SmallCapitalShip, BigCapitalShip, Mothership"`

How can this ship fire at probes if probes' AttackFamily is NonCombat?
Also, what is the point of multiple comas?

**Comment by cloaked2222** [comment]
The CanAttack line is attack priorities. Anything not in that line just gets treated as a very low priority. The commas further lower priorities, so in the line above Resource is prioritized quite a bit over Capturer.

I did a thorough review on the CanAttack lines for the 2.205 patch, and they are good as is other than the OP. Just before v2.0 was released ints would prioritize resource collectors before other ints, rofl. Glad I caught that one before the patch shipped...

Also the line you pasted is from v2.1. Be sure to use 2.3 or 2.205 files!

**Comment by Echo1707** [comment]
That line is actually on 2.205 files (https://github.com/HW-PlayersPatch/2.3/blob/Bleeding-Edge/2.205/ship/kus_heavycorvette/kus_heavycorvette.ship), but that doesn't change the fact that I really shouldn't be modding when I'm supposed to be sleeping :(

Watching again that line makes me ask... do we want heavy corvettes to target frigates first now that they are getting buffed vs them but nerfed vs other corvettes?

I also noticed that resource controllers have an AttackFamily of ResourceLarge, but I don't recall any ship having ResourceLarge in their attack priorities... Maybe ships like bombers, laser corvettes, pulsars, heavy corvettes, ion frigs, (unsure about DDs) and HCs/BCs should target refineries/controllers before collectors as per https://github.com/HW-PlayersPatch/2.3/issues/26#issuecomment-397489474 ideal values?

**Comment by cloaked2222** [comment]
My bad, ya that heavy corv line you posted was from 2.205. But that line was significantly improved in 2.3 long ago:
addAbility(NewShipType,"CanAttack",1,0,1,1,0.35,1,"Corvette, Corvette_hw1, Frigate, SmallCapitalShip, BigCapitalShip, Resource, Utility,,,,,,, Fighter, Fighter_hw1, Swarmer, Mothership","frontal_HeavyCorvette",
https://github.com/HW-PlayersPatch/2.3/blob/master/2.3/ship/kus_heavycorvette/kus_heavycorvette.ship

Be sure to use a 2.3 file if it exists, and only use 2.205 if it doesn't.

> "Watching again that line makes me ask... do we want heavy corvettes to target frigates first now that they are getting buffed vs them but nerfed vs other corvettes?"
Making heavies bad vs corvs is not consistent hw1c or HWR and is not gonna fly. I still need to review Fear's weapon changes, and tweak as needed.

Target priorities can be important vs attack ships (especially for swarm), but they aren't that important vs utility type ships further down the priority list - which the player should be manually targeting as needed. Things towards the bottom of the priority list like Mothership barely matter. hw2c collectors "AttackFamily"="Resource". I believe Relic/Gearbox intentionally left resource units at the bottom/off of many lists so that cpu players wouldn't cripple the income for new players. I really wouldn't waste your time on perfecting target priorities, they're pretty good as is other than your great idea from the OP. Get your sleep! =)

**Comment by Echo1707** [comment]
Here is the pull request: https://github.com/HW-PlayersPatch/2.3/pull/74

I'm also adding Swarmers priority and attack style vs them to relevant Taiidan ships (should make it easier for modders to implement Taiidan as the playable race in campaign).

Heavy corvettes shouldn't be bad vs other corvettes, just received a small nerf vs them and a big buff vs frigates: https://github.com/HW-PlayersPatch/2.3/blob/Bleeding-Edge/Props/Taiidan_Changes_Prop.md#heavy-corvettes

I have another question for when you finish reviewing heavy corvettes' and assault frigs' weapons changes: assault frigs currently target frigates as first priority and corvettes as their second priority. Maybe it should be the other way around? They are good vs both, but enemy frigates are easier to target and take down 1 by 1 if you tell your frigates to focus them.

While cheking HCs, I noticed this (just a FYI, I didn't change it; seems like many ships have only one "RepCap"):
- Kushan: addAbility(NewShipType,"CanBeRepaired","RepCap","RepCap");
- Taiidan: addAbility(NewShipType,"CanBeRepaired","RepCap");

**Comment by cloaked2222** [comment]
Great move on swarmers. Maybe someday that could be a 2.3 feature. =)

Ya frigates should be just below corvettes in the hw1 assault frigate attack priority.

If you don't see any other ships with 2x RepCap, it looks like it could be a GBX typo. But since you can repair the Kus Heavy Cruiser regardless, I guess it don't matter so I'd just leave it be.
