### ISSUE TITLE
Defenders

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#71]
Thread to discuss defender changes.

Current plan is to make them more like hw1c.

Fear has a branch for them here: https://github.com/HW-PlayersPatch/2.3/tree/defenders
Fear's Changes:
- Unit caps match interceptors
- Build time to 5sec
- HP to 340 (this was while sidearmourdamage was 0.9)

**Comment by Echo1707** [comment]
I don't know how I feel about this. Unlocking defenders costs time and RUs, so I'd expect them to have some perks over basic ints. Do they still win in a match up vs ints with same RUs spent or same build time?
