### ISSUE TITLE
Test Data Needed for many changes

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#8]
### Vaygr

**Comment by cloaked2222** [comment]
@Echo1707 - Just an FYI, I wouldn't spend much time making general test data until we have a candidate b8 ready. Test data for specific b8 open issues are welcome though, such as all ships vs collectors. Be sure to let us know your detailed test plan first tho, so we can advise/recommend any changes (like x ships vs x colls).

**Comment by cloaked2222** [comment]
As an FYI, I still haven't had a chance to review and test any of Fear's May/June weapon changes. -_-

**Comment by cloaked2222** [comment]
I think I figured out how light corvettes ended up OP between build 5 (Swarm Balancing 120217.xlsx) and build 7!
"Build 7: Kushan/Taiidan corvettes now respond quickly to certain attack orders, without a long delay. "
![image](https://user-images.githubusercontent.com/18016573/43117050-c8092d32-8ed8-11e8-8533-c374e8e82054.png)
That bug fix shifted balance a bit. -_- Testing is soo important!

**Comment by cloaked2222** [comment]
Pie in the sky
