### ISSUE TITLE
Build 8 Release

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#84]
Targeting this Wednesday to release Bleeding-Edge as build 8. =D

@Echo1707 if you have time this week, can you try to wrap these up:
1. https://github.com/HW-PlayersPatch/2.3/pull/74
2. https://github.com/HW-PlayersPatch/2.3/issues/70

**Comment by Echo1707** [comment]
If you think bleeding-edge is fine, then great :) So you are fine with Fear's changes to HW1 weapons too?

There are still many issues open that are targetted to build 8 though, like times for ships vs collectors https://github.com/HW-PlayersPatch/2.3/issues/26

**Comment by cloaked2222** [comment]
Haha, ya.

Now that all the build 8 .ship changes are done, I plan to review/test all weapon changes tomorrow. That should knock out the remaining open issues for build 8.

Putting a lot of time in this week to get this update shipped!

**Comment by Echo1707** [comment]
I'm not opening an issue abuot this because I haven't tested this yet myself, but a guy on Discord (RoBeY aka Gaudrik) claims to have made some tests with Fear and they discovered that bombers are overperforming vs corvettes.

**Comment by cloaked2222** [comment]
Ya bombers are already nerfed vs corvs for b8. I just updated the slider to say "2+" is Expert.

No problem, just make a pull requests for the parades. I also added you as a contributor on the 2.3 steam page, so be sure to accept. :)

**Comment by gaudrik** [comment]
Hello and good work!
Also I’m available for testing if you need help. (Fear gave me the link a while back Incase you’re wondering)

-RoBeY

**Comment by Echo1707** [comment]
Hello RoBeY, glad to have you with us ^^

**Comment by cloaked2222** [comment]
Hey RoBeY! Sounds good, I'll ping you on steam if I've got some free time Wednesday.

**Comment by gaudrik** [comment]
I sent you a DM on discord, I can’t have friends on steam yet haha.
