### ISSUE TITLE
Parade Formations

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#90]
Paraded formations should be updated so resource collectors go to the optimal location when they un-dock. Vaygr and Taiidan have to fight collectors at the start of the game. For vaygr, you need to move the flagship up, but colls are trying to go up and over the flagship at the same time.... For taiidan, you need to move the flagship down, but colls are trying to go down at the same time, and tend to get stuck on that claw.

Hiig: Great as is.
Vay: They go to the right side and above the ship. They should go to the left side and below the ship.
Kus: They go to the left side and below the ship. This is OK as is.
Tai: They go to the right side and below the ship. They should go above the ship. If anything else can be done to avoid the claw collision, that'd be great.

See scripts\formations for the parade files, they're pretty straight-forward. Also be sure to test with a full fleet (edit starting fleet files).

@Echo1707 - Want to work on this one?

Also got kinda sidetracked today, so gonna target Wednesday August 1st for build 8 instead.

**Comment by Echo1707** [comment]
## Taiidan

paradeSlot("Tai_ResourceCollector",	{-2100, 300, -200},{0,0,1},	{-1,0,0},	210);
paradeSlot("Tai_ResourceController",{-2100, 300, -600},{0,0,1},	{-1,0,0},	455);

![homeworldrm 2018-07-23 12-50-49-00](https://user-images.githubusercontent.com/39770560/43074042-1a02ab0c-8e7c-11e8-8770-9be155e57ceb.png)

![homeworldrm 2018-07-23 12-52-20-48](https://user-images.githubusercontent.com/39770560/43074045-1e07098c-8e7c-11e8-92ca-a425281be103.png)

## Vaygr

`paradeSlot("Tai_ResourceCollector",	{-2100, 300, -200},	{0,0,1},	{-1,0,0},	210);`
`paradeSlot("Tai_ResourceController",	{-2100, 300, -600},	{0,0,1},	{-1,0,0},	455);`

https://vimeo.com/281248986

**Comment by cloaked2222** [comment]
Great work!!!

Shipyards are limited to one on all unit caps, so its not a big deal.

**Comment by Echo1707** [comment]
It's nothing, really :)

![homeworldrm 2018-07-24 21-22-20-42](https://user-images.githubusercontent.com/39770560/43161334-186ea02c-8f88-11e8-9e8e-1e24d481104e.png)

I'd like to have some more ships parade on the right side, it feels empty compared to the left. I wonder if I can have them parade like Taiidans (or instead of having "horizontal planes" of ships of the same size (fighters on top, corvetes in the middle, frigates below), having "vertical walls" of ships of the same size (fighters forward, corvettes in the middle and frigates on the back). The problem I see with both these layouts is that ships become hard to distinguish and select. Also, I don't know if there are objects/asteroids that would interfere in the campaign (M06 comes to mind: the last thing I want is having frigates hyperspacing or strikecrafts slamming into asteroids while parading at mission start).

**Comment by cloaked2222** [comment]
I wouldn't change Kushan's parade much from classic. Parade's are kinda a distinct race characteristic. But some minor changes like these would be ok:
- Move resource units to the right side, this is the ideal side anyways since they un-dock on the right.
- Could move campaign capture-able fighters/corvs to the right side.

Right side will also look a lot more filled out if you have say 70 interceptors and 42 heavy corvettes.

**Comment by Echo1707** [comment]
![homeworldrm 2018-07-24 21-00-08-12](https://user-images.githubusercontent.com/39770560/43193703-0486fff4-9001-11e8-875e-f687bc2b9d71.png)

Since ints and bombers are capped at 70 anyway, can we remove those two lines?

**Comment by cloaked2222** [comment]
Larger unit caps will have more than 70 of course.

Cya!

**Comment by Echo1707** [comment]
Then why scouts are not listed in the image above? I have 5 of them, but they don't show up.

![homeworldrm 2018-07-30 14-00-40-17](https://user-images.githubusercontent.com/39770560/43396640-7619c23c-9402-11e8-8a81-73377edca194.png)

In this image, fighters are all listed, which is ok, but then why I don't see how many corvettes are gunships and how many are pulsars? Same thing for frigates: why I don't get another line telling them that all my 21 frigs are torps?

Or we can view things the other way around (which is how I indented my original question but didn't express it very well): in the image of 5 days ago, we can see that corvettes and frigates are not listed type-by-type, but are listed only ships that have a different (of course smaller) limit/cap than the family they are in (i.e. max 14 of 42 corvettes can be salvettes and max 4 of 42 corvettes can be minelayers).

So, which is better, to show how many scouts/ints/bombers/defenders/cloaked fighters/defense fighters/lance fighters, light/heavy/multigun/repair corvettes and support/assault/ion/flak/torp/heavy missile on has, or ot show only the units that have a different unit cap than the one for their family?

Hope it's more clear now :)

**Comment by cloaked2222** [comment]
Oh I see what you mean now. Move this info to a separate issue/thread to discuss the unit cap display for build 9.

Kushan parade is gonna have to wait for b9.

**Comment by Echo1707** [comment]
As a reminder for myself, any change to the Kushan research ship parade position must be at least compatible with the Scaffold in M01 and M03.
Another check might be needed for M06.

**Comment by cloaked2222** [comment]
Fanthomas said this:
The 'parade' formation is not doing what you would except from classic HW1 (the pre-hyperspace lineup) when executed with the mothership selected. Instead, ships get behind the mothership in scattered arrays. Like so:
https://steamuserimages-a.akamaihd.net/ugc/938330377459545569/4C979F94E571F239106DA23E4EF2A9A629A8B34F/
Could the 'parade' formation become the default pre- and post-hyperspace formation please?

**Comment by cloaked2222** [comment]
Pie in the sky
